# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0d9d87a89b07568bb2a407d78ec9ee521ebac26c8473ef0a492cdbae10bddd874dcd8d648767b4085a0b43e9099ef034ce0968269df9ba9010acb1ce20d7f4ec

test:
  secret_key_base: fd5a4a4b7222b480000f7d72e71c791e311f78fc3ba3c9971b5017b9290d1778e8e4e6aa630169920b07dd4eb42b058bbffa068c0e1c585e3a76c058fddf6e2c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
